import tkinter as tk

# Fonction pour mettre à jour l'affichage de la calculatrice
def update_display(value):
    current_text = display_label["text"]
    if current_text == "0":
        display_label["text"] = value
    else:
        display_label["text"] += value

# Fonction pour effacer l'affichage
def clear_display():
    display_label["text"] = "0"

# Fonction pour évaluer l'expression mathématique
def calculate():
    expression = display_label["text"]
    try:
        result = eval(expression)
        display_label["text"] = str(result)
    except Exception as e:
        display_label["text"] = "Error"

# Création de la fenêtre principale
root = tk.Tk()
root.title("Simple Calculator")

# Création du widget pour l'affichage
display_label = tk.Label(root, text="0", font=("Helvetica", 20), width=15, anchor="e")
display_label.grid(row=0, column=0, columnspan=4, padx=10, pady=10)

# Liste des boutons
buttons = [
    ("7", 1, 0), ("8", 1, 1), ("9", 1, 2), ("/", 1, 3),
    ("4", 2, 0), ("5", 2, 1), ("6", 2, 2), ("*", 2, 3),
    ("1", 3, 0), ("2", 3, 1), ("3", 3, 2), ("-", 3, 3),
    ("0", 4, 0), (".", 4, 1), ("=", 4, 2), ("+", 4, 3)
]

# Création des boutons
for (text, row, column) in buttons:
    btn = tk.Button(root, text=text, font=("Helvetica", 15), width=3, height=1,
                    command=lambda t=text: update_display(t) if t != "=" else calculate())
    btn.grid(row=row, column=column, padx=5, pady=5)

# Bouton pour effacer l'affichage
clear_button = tk.Button(root, text="C", font=("Helvetica", 15), width=3, height=1, command=clear_display)
clear_button.grid(row=5, column=0, columnspan=2, padx=5, pady=5)

# Bouton pour fermer la calculatrice
quit_button = tk.Button(root, text="Quit", font=("Helvetica", 15), width=3, height=1, command=root.quit)
quit_button.grid(row=5, column=2, columnspan=2, padx=5, pady=5)

# Lancement de la boucle principale
root.mainloop()

